POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "User y added this blog",
    "author": "Jone",
    "url": "google.com",
    "likes": 137,
    "userId": "5d492c8978ffdc14e528273e"
}